### redis server ip address required for the ssh and scp connections 
### cluster cache endpoint required to be added to Spring-boot java code
### cluster cache endpoint required for the command to start connection to redis cache:
### cd redis-stable; src/redis-cli -c -h <our configuration endpoint without the :6379> -p 6379

pipeline {
   agent any

   stages {
     stage('Polling SCM' ) {
         steps {
            echo 'Cloning code from remote repository'
	    sh '''
            cd /tmp/
	    mkdir placeholder || true
            cd placeholder/
            git clone https://github.com/Saturn-cloud/spring-boot-elasticache-redis-tutorial.git
            '''
      	 }  
       }
      stage('Compile' ) {
         steps {
            echo 'Compiling code...'
	    sh '''
            cd /tmp/placeholder/spring-boot-elasticache-redis-tutorial
            mvn clean package
            '''
      	 }  
       }
      stage('Build' ) {
         steps {
            echo 'Preparing for code deployment'
            sh '''
            sudo ssh -o StrictHostKeychecking=no -i /home/ec2-user/.ssh/first_keys ec2-user@<redis.server.ip.address> '
	    cd /home/ec2-user/redis-stable
            src/redis-cli -c -h <rediscluster configuration endpoint without the port number> -p 6379 '
            '''
      	 }
       }
      stage('Deploy' ) {
         steps {
            echo 'Deploying app to Redis-server'
	    sh '''
            sudo scp -i /home/ec2-user/.ssh/first_keys /tmp/placeholder/spring-boot-elasticache-redis-tutorial/target/example-0.0.1-SNAPSHOT.jar ec2-user@<redis.server.ip.address>:/tmp/
	    sudo ssh -i /home/ec2-user/.ssh/first_keys ec2-user@<redis.server.ip.address> '
	    sudo pkill java || true
	    cd /tmp/
	    rm -rf target/ || true
	    mkdir target
	    mv example-0.0.1-SNAPSHOT.jar target
	    cd target
            nohup java -jar example-0.0.1-SNAPSHOT.jar & 
	    exit '
            '''
      	 }
       }
      stage('Cleanup' ) {
         steps {
            echo 'Removing used files and folders'
	    sh '''
	    cd /tmp/
	    sudo rm -rf placeholder/
          '''
      	 }
       }
    }  
}